FROM bitnami/spark:3.5.1

USER root

RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install --upgrade pip

COPY requirements.txt /app/requirements.txt

RUN pip3 install -r /app/requirements.txt

WORKDIR /app
COPY jobs/ /app/jobs/

CMD [ "bash" ]
