x-pipeline-defaults: &pipeline-template
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./:/app/application
  # ports:
  #   - "4040:4040"
  command: ["/app/application/entrypoint.sh"]
  networks:
    - datamasterylab
  deploy:
    resources:
      limits:
        memory: 2g
        cpus: '1.0'

x-common-env: &common-env
  POSTGRES_JDBC_URL: jdbc:postgresql://postgres:5432/
  RAW_PATH: hdfs://namenode:9000/RAW/
  WAREHOUSE_PATH: hdfs://namenode:9000/user/hive/warehouse/
  WAREHOUSE_DB: process_data
  WAREHOUSE_DB_PATH: hdfs://namenode:9000/user/hive/warehouse/process_data.db/
  JDBC_USER: hive
  JDBC_PASSWORD: hive

services:

  vehicle_data1:
    <<: *pipeline-template
    container_name: vehicle_data1
    environment:
      <<: *common-env
      PY_FILE: consumer_kafka.py
      KAFKA_TOPIC: vehicle_data
      TOPIC_KEY: vehicle

  vehicle_data2:
    <<: *pipeline-template
    container_name: vehicle_data2
    environment:
      <<: *common-env
      PY_FILE: consumer_hdfs.py
      KAFKA_TOPIC: vehicle_data
      TOPIC_KEY: vehicle

  gps_data1:
    <<: *pipeline-template
    container_name: gps_data1
    environment:
      <<: *common-env
      PY_FILE: consumer_kafka.py
      KAFKA_TOPIC: gps_data
      TOPIC_KEY: gps

  gps_data2:
    <<: *pipeline-template
    container_name: gps_data2
    environment:
      <<: *common-env
      PY_FILE: consumer_hdfs.py
      KAFKA_TOPIC: gps_data
      TOPIC_KEY: gps

  traffic_data1:
    <<: *pipeline-template
    container_name: traffic_data1
    environment:
      <<: *common-env
      PY_FILE: consumer_kafka.py
      KAFKA_TOPIC: traffic_data
      TOPIC_KEY: traffic

  traffic_data2:
    <<: *pipeline-template
    container_name: traffic_data2
    environment:
      <<: *common-env
      PY_FILE: consumer_hdfs.py
      KAFKA_TOPIC: traffic_data
      TOPIC_KEY: traffic

  weather_data1:
    <<: *pipeline-template
    container_name: weather_data1
    environment:
      <<: *common-env
      PY_FILE: consumer_kafka.py
      KAFKA_TOPIC: weather_data
      TOPIC_KEY: weather

  weather_data2:
    <<: *pipeline-template
    container_name: weather_data2
    environment:
      <<: *common-env
      PY_FILE: consumer_hdfs.py
      KAFKA_TOPIC: weather_data
      TOPIC_KEY: weather

  emergency_data1:
    <<: *pipeline-template
    container_name: emergency_data1
    environment:
      <<: *common-env
      PY_FILE: consumer_kafka.py
      KAFKA_TOPIC: emergency_data
      TOPIC_KEY: emergency

  emergency_data2:
    <<: *pipeline-template
    container_name: emergency_data2
    environment:
      <<: *common-env
      PY_FILE: consumer_hdfs.py
      KAFKA_TOPIC: emergency_data
      TOPIC_KEY: emergency

networks:
  datamasterylab:
    external: true
    name: "datamasterylab"
